#!/bin/bash

# 16-08-2019
# Nicolas Roudninski
#

opt=$1

lastversions=( $( curl -fsSL 'https://download.nextcloud.com/server/releases/' |tac|tac| \
	grep -oE 'nextcloud-[[:digit:]]+(\.[[:digit:]]+){2}' | \
	grep -oE '[[:digit:]]+(\.[[:digit:]]+){2}' | \
	sort -urV ) )

installedversion=`cat /usr/src/nextcloud/version.php 2>/dev/null | grep OC_VersionString | cut -d\' -f 2`

while getopts il option
do
	case "${option}" in
		i) echo "Installed version : $installedversion";;
		l) echo "Last version : $lastversions";;
	esac
done	
exit 0
